export const API_URL: string = 'http://localhost:8080/';
export const COURSE_LIST: string = 'forum/courses/filter/';
export const THREAD_LIST: string = 'forum/posts/top?noOfPosts=';
export const THREAD_LIST_10: string = 'forum/posts/top/10';
export const THREAD_REPLIES: string = 'forum/posts/clicked';
export const POST_COURSE: string = 'forum/courses/new';
export const USERS: string = 'forum/users/';
export const REGISTER_USER = 'register';
export const LOGIN_USER = 'login';
export const USER_LIKES_POST = 'post';
